Repository FACG5/Qattan-foundation, pull requests merged in 2018-10, with the labels that each got.

#31 Add server files
  src/app.js
  src/index.js
Labels: awaiting-review

#32 Add Router file
  src/controllers/index.js
Labels: awaiting-review

#33 Adding Queries for ticket
  src/model/queries/ticket.js
Labels: awaiting-review

#30 header and footer
  package-lock.json
  public/css/master.css
  src/app.js
  src/views/layouts/main.hbs
  src/views/partials/footer.hbs
  src/views/partials/head.hbs
  src/views/partials/header.hbs
  src/views/partials/sidebar.hbs
Labels: awaiting-review

#35 Edit main.hbs
  package-lock.json
  src/views/layouts/main.hbs
  src/views/partials/headerManager.hbs
  src/views/partials/sidebarManager.hbs
Labels: awaiting-review

#42 Support page
  src/controllers/index.js
  src/controllers/support.js
  src/model/queries/ticket.js
  src/views/support.hbs
Labels: awaiting-review

#48 Support details
  public/js/updateTicket.js
  src/controllers/index.js
  src/controllers/supportDetails.js
  src/model/queries/ticket.js
  src/views/loans.hbs
  src/views/support.hbs
  src/views/supportDetails.hbs
Labels: awaiting-review

#49 Loan details
  public/js/updateLoan.js
  src/controllers/index.js
  src/controllers/loanDetails.js
  src/views/loanDetails.hbs
Labels: awaiting-review

#54 User experience
  public/css/homeManager.css
  public/css/master.css
  public/js/updateLoan.js
  src/controllers/homeManager.js
  src/controllers/index.js
  src/controllers/notSolved.js
  src/controllers/solved.js
  src/controllers/supportDetails.js
  src/controllers/tickets.js
  src/model/database/dbDemo.sql
  src/model/queries/ticket.js
  src/views/homeManager.hbs
  src/views/layouts/main.hbs
  src/views/loans.hbs
  src/views/notSolved.hbs
  src/views/partials/headerManager.hbs
  src/views/solved.hbs
  src/views/support.hbs
  src/views/tickets.hbs
Labels: awaiting-review

#62 Employee home
  .eslintrc.json
  public/css/employee.css
  public/js/employee.js
  src/controllers/employee.js
  src/controllers/index.js
  src/views/addTicket.hbs
  src/views/employee.hbs
  src/views/layouts/main.hbs
  src/views/partials/header.hbs
Labels: Done, awaiting-review

#66 Employee home
  public/css/employee.css
  public/js/employee.js
  src/controllers/employee.js
  src/model/queries/inventory.js
  src/views/employee.hbs
Labels: Done, awaiting-review, in-review

#68 Add ticket
  public/css/employee.css
  public/css/form.css
  public/js/addTicket.js
Labels: awaiting-review

#51 updating inventory branch
  package-lock.json
  package.json
  public/css/error.css
  public/css/master.css
  public/js/inventory.js
  public/js/login.js
  public/js/updateInventoryPage.js
  src/app.js
  src/controllers/error.js
  src/controllers/homeManager.js
  src/controllers/index.js
  src/controllers/inventory.js
  src/controllers/validate.js
  src/middlewares.js
  src/model/database/dbBuild.sql
  src/model/database/dbDemo.sql
  src/model/queries/inventory.js
  src/views/error.hbs
  src/views/inventory.hbs
  src/views/layouts/error.hbs
  src/views/layouts/main.hbs
  src/views/partials/sidebarManager.hbs
  src/views/updateInventoryPage.hbs
Labels: awaiting-review, merge-ready, priority-1

#73 Validation for add ticket page
  public/css/employee.css
  public/js/addTicket.js
  src/controllers/addTicket.js
Labels: awaiting-review

#71 Update ticket pages validation
  public/js/updateLoan.js
  public/js/updateTicket.js
  src/controllers/loanDetails.js
  src/controllers/supportDetails.js
Labels: awaiting-review

#69 Detalis pages
  public/css/details.css
  src/controllers/loanDetails.js
  src/controllers/supportDetails.js
  src/views/loanDetails.hbs
  src/views/supportDetails.hbs
Labels: awaiting-review

#74 Report
  public/css/master.css
  public/css/report.css
  public/js/report.js
  src/controllers/index.js
  src/controllers/reports.js
  src/model/queries/ticket.js
  src/views/reports.hbs
Labels: awaiting-review

#75 Fixed error
  package-lock.json
  public/css/employee.css
  public/css/form.css
  public/css/login.css
  public/css/master.css
  public/js/addTicket.js
  public/js/login.js
  public/js/updateTicket.js
  src/controllers/inventory.js
  src/controllers/supportDetails.js
  src/model/database/dbBuild.sql
  src/views/inventory.hbs
Labels: awaiting-review

#78 Fixed working
  public/js/addTicket.js
Labels: awaiting-review

#76 adding authentication for all pages
  public/js/addTicket.js
  src/controllers/addTicket.js
  src/controllers/employee.js
  src/controllers/inventory.js
  src/controllers/loanDetails.js
  src/controllers/loans.js
  src/controllers/notSolved.js
  src/controllers/reports.js
  src/controllers/solved.js
  src/controllers/support.js
  src/controllers/supportDetails.js
  src/controllers/tickets.js
  src/views/employee.hbs
Labels: awaiting-review
